import { MovieDetailDTO, MovieDTO } from '../types'

export const movieDetail: MovieDetailDTO = {
    adult: false,
    backdrop_path: '/1Rr5SrvHxMXHu5RjKpaMba8VTzi.jpg',
    belongs_to_collection: {
        id: 531241,
        name: 'Spider-Man (Avengers) Collection',
        poster_path: '/nogV4th2P5QWYvQIMiWHj4CFLU9.jpg',
        backdrop_path: '/AvnqpRwlEaYNVL6wzC4RN94EdSd.jpg',
    },
    budget: 200000000,
    genres: [
        {
            id: 28,
            name: 'Action',
        },
        {
            id: 12,
            name: 'Adventure',
        },
        {
            id: 878,
            name: 'Science Fiction',
        },
    ],
    homepage: 'https://www.spidermannowayhome.movie',
    id: 634649,
    imdb_id: 'tt10872600',
    original_language: 'en',
    original_title: 'Spider-Man: No Way Home',
    overview:
        'Peter Parker is unmasked and no longer able to separate his normal life from the high-stakes of being a super-hero. When he asks for help from Doctor Strange the stakes become even more dangerous, forcing him to discover what it truly means to be Spider-Man.',
    popularity: 20686.826,
    poster_path: '/1g0dhYtq4irTY1GPXvft6k4YLjm.jpg',
    production_companies: [
        {
            id: 420,
            logo_path: '/hUzeosd33nzE5MCNsZxCGEKTXaQ.png',
            name: 'Marvel Studios',
            origin_country: 'US',
        },
        {
            id: 84041,
            logo_path: '/nw4kyc29QRpNtFbdsBHkRSFavvt.png',
            name: 'Pascal Pictures',
            origin_country: 'US',
        },
        {
            id: 5,
            logo_path: '/71BqEFAF4V3qjjMPCpLuyJFB9A.png',
            name: 'Columbia Pictures',
            origin_country: 'US',
        },
    ],
    production_countries: [
        {
            iso_3166_1: 'US',
            name: 'United States of America',
        },
    ],
    release_date: '2021-12-15',
    revenue: 638000000,
    runtime: 148,
    spoken_languages: [
        {
            english_name: 'English',
            iso_639_1: 'en',
            name: 'English',
        },
        {
            english_name: 'Tagalog',
            iso_639_1: 'tl',
            name: '',
        },
    ],
    status: 'Released',
    tagline: 'The Multiverse unleashed.',
    title: 'Spider-Man: No Way Home',
    video: false,
    vote_average: 8.6,
    vote_count: 1886,
    videos: {
        results: [
            {
                iso_639_1: 'en',
                iso_3166_1: 'US',
                name: 'Check It Out',
                key: 'xGjmWfbLPzQ',
                site: 'YouTube',
                size: 1080,
                type: 'Teaser',
                official: true,
                published_at: '2021-12-18 17:00:39 UTC',
                id: '61c180412ac4990093d2e176',
            },
            {
                iso_639_1: 'en',
                iso_3166_1: 'US',
                name: 'SPIDER-MAN: NO WAY HOME - Cast Catch-Up',
                key: 'Ylufh8C79BI',
                site: 'YouTube',
                size: 1080,
                type: 'Featurette',
                official: true,
                published_at: '2021-12-17 23:00:30 UTC',
                id: '61bdcd960143250065da66c6',
            },
            {
                iso_639_1: 'en',
                iso_3166_1: 'US',
                name: 'Imagine',
                key: 'UV2ZWTSHjSs',
                site: 'YouTube',
                size: 1080,
                type: 'Teaser',
                official: true,
                published_at: '2021-12-12 13:00:27 UTC',
                id: '61b68b940443c90087493d8e',
            },
            {
                iso_639_1: 'en',
                iso_3166_1: 'US',
                name: 'Outed',
                key: 'kBS44EwDER4',
                site: 'YouTube',
                size: 1080,
                type: 'Clip',
                official: false,
                published_at: '2021-12-10 20:33:28 UTC',
                id: '61b6d6edcb75d100612d923f',
            },
            {
                iso_639_1: 'en',
                iso_3166_1: 'US',
                name: 'Return of the Villains Vignette',
                key: 'w5oVmO5kYEE',
                site: 'YouTube',
                size: 1080,
                type: 'Featurette',
                official: true,
                published_at: '2021-12-08 17:00:47 UTC',
                id: '61b6eedc7d5f4b009125fa9b',
            },
            {
                iso_639_1: 'en',
                iso_3166_1: 'US',
                name: 'Fame',
                key: 'SzdyGglS4zM',
                site: 'YouTube',
                size: 1080,
                type: 'Teaser',
                official: true,
                published_at: '2021-12-03 16:18:50 UTC',
                id: '61b68bc14cd912001aed534d',
            },
            {
                iso_639_1: 'en',
                iso_3166_1: 'US',
                name: 'Dude',
                key: '22oiqgtV6hw',
                site: 'YouTube',
                size: 1080,
                type: 'Teaser',
                official: true,
                published_at: '2021-11-29 05:00:03 UTC',
                id: '61a4c1ff180dea00988103ae',
            },
            {
                iso_639_1: 'en',
                iso_3166_1: 'US',
                name: 'Together',
                key: 'fx9miIKrvIo',
                site: 'YouTube',
                size: 1080,
                type: 'Teaser',
                official: true,
                published_at: '2021-11-27 17:19:35 UTC',
                id: '61a4c190869e750093ed62ab',
            },
            {
                iso_639_1: 'en',
                iso_3166_1: 'US',
                name: 'Strange',
                key: 'I5Js6wam7e4',
                site: 'YouTube',
                size: 1080,
                type: 'Teaser',
                official: true,
                published_at: '2021-11-24 20:06:22 UTC',
                id: '61a4c12905822400642693e9',
            },
            {
                iso_639_1: 'en',
                iso_3166_1: 'US',
                name: 'Spider Bite',
                key: 'M6ix8Q50OaM',
                site: 'YouTube',
                size: 1080,
                type: 'Teaser',
                official: true,
                published_at: '2021-11-23 00:47:32 UTC',
                id: '61a4c0f30231f20061539241',
            },
            {
                iso_639_1: 'en',
                iso_3166_1: 'US',
                name: 'Official IMAX® Trailer',
                key: 'pBvH8hvnJPk',
                site: 'YouTube',
                size: 1080,
                type: 'Trailer',
                official: true,
                published_at: '2021-11-18 23:27:29 UTC',
                id: '61982e61e2ff32004371953a',
            },
            {
                iso_639_1: 'en',
                iso_3166_1: 'US',
                name: 'Official Trailer',
                key: 'JfVOs4VSpmA',
                site: 'YouTube',
                size: 1080,
                type: 'Trailer',
                official: true,
                published_at: '2021-11-17 01:30:05 UTC',
                id: '61945b8a4da3d4002992d5a6',
            },
            {
                iso_639_1: 'en',
                iso_3166_1: 'US',
                name: 'Official Teaser Trailer',
                key: 'WgU7P6o-GkM',
                site: 'YouTube',
                size: 1080,
                type: 'Trailer',
                official: true,
                published_at: '2021-08-24 01:40:05 UTC',
                id: '6124694a534661005cd0b8a7',
            },
            {
                iso_639_1: 'en',
                iso_3166_1: 'US',
                name: 'The New Spider-Man Title is…',
                key: 'iqyPvdsOWKk',
                site: 'YouTube',
                size: 1080,
                type: 'Teaser',
                official: true,
                published_at: '2021-02-24 17:44:20 UTC',
                id: '60378fdcd132d60040a45d96',
            },
        ],
    },
}

export const movies: Array<MovieDTO> = [
    {
        adult: false,
        backdrop_path: '/1Rr5SrvHxMXHu5RjKpaMba8VTzi.jpg',
        genre_ids: [28, 12, 878],
        id: 634649,
        original_language: 'en',
        original_title: 'Spider-Man: No Way Home',
        overview:
            'Peter Parker is unmasked and no longer able to separate his normal life from the high-stakes of being a super-hero. When he asks for help from Doctor Strange the stakes become even more dangerous, forcing him to discover what it truly means to be Spider-Man.',
        popularity: 20686.826,
        poster_path: '/1g0dhYtq4irTY1GPXvft6k4YLjm.jpg',
        release_date: '2021-12-15',
        title: 'Spider-Man: No Way Home',
        video: false,
        vote_average: 8.6,
        vote_count: 1839,
    },
    {
        adult: false,
        backdrop_path: '/eENEf62tMXbhyVvdcXlnQz2wcuT.jpg',
        genre_ids: [878, 28, 12],
        id: 580489,
        original_language: 'en',
        original_title: 'Venom: Let There Be Carnage',
        overview:
            'After finding a host body in investigative reporter Eddie Brock, the alien symbiote must face a new enemy, Carnage, the alter ego of serial killer Cletus Kasady.',
        popularity: 7992.617,
        poster_path: '/rjkmN1dniUHVYAtwuV3Tji7FsDO.jpg',
        release_date: '2021-09-30',
        title: 'Venom: Let There Be Carnage',
        video: false,
        vote_average: 7.2,
        vote_count: 4869,
    },
    {
        adult: false,
        backdrop_path: '/7ajHGIAYNMiIzejy1LJWdPrcAx8.jpg',
        genre_ids: [28, 35, 80, 53],
        id: 512195,
        original_language: 'en',
        original_title: 'Red Notice',
        overview:
            "An Interpol-issued Red Notice is a global alert to hunt and capture the world's most wanted. But when a daring heist brings together the FBI's top profiler and two rival criminals, there's no telling what will happen.",
        popularity: 3496.837,
        poster_path: '/lAXONuqg41NwUMuzMiFvicDET9Y.jpg',
        release_date: '2021-11-04',
        title: 'Red Notice',
        video: false,
        vote_average: 6.8,
        vote_count: 2156,
    },
    {
        adult: false,
        backdrop_path: '/cinER0ESG0eJ49kXlExM0MEWGxW.jpg',
        genre_ids: [28, 12, 14],
        id: 566525,
        original_language: 'en',
        original_title: 'Shang-Chi and the Legend of the Ten Rings',
        overview:
            'Shang-Chi must confront the past he thought he left behind when he is drawn into the web of the mysterious Ten Rings organization.',
        popularity: 3100.52,
        poster_path: '/1BIoJGKbXjdFDAqUEiA2VHqkK1Z.jpg',
        release_date: '2021-09-01',
        title: 'Shang-Chi and the Legend of the Ten Rings',
        video: false,
        vote_average: 7.8,
        vote_count: 4426,
    },
    {
        adult: false,
        backdrop_path: '/tTlAA0REGPXSZPBfWyTW9ipIv1I.jpg',
        genre_ids: [28, 12, 878, 18],
        id: 315635,
        original_language: 'en',
        original_title: 'Spider-Man: Homecoming',
        overview:
            'Following the events of Captain America: Civil War, Peter Parker, with the help of his mentor Tony Stark, tries to balance his life as an ordinary high school student in Queens, New York City, with fighting crime as his superhero alter ego Spider-Man as a new threat, the Vulture, emerges.',
        popularity: 2968.44,
        poster_path: '/c24sv2weTHPsmDa7jEMN0m2P3RT.jpg',
        release_date: '2017-07-05',
        title: 'Spider-Man: Homecoming',
        video: false,
        vote_average: 7.4,
        vote_count: 17467,
    },
]
